name: Deploy Databricks Bundle

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'resources/**'
      - 'databricks.yml'

jobs:
  # --- JOB 1: VALIDACIÓN PREVIA ---
  validate:
    runs-on: ubuntu-latest
    # Queremos que la salida de este job esté disponible para otros.
    outputs:
      commit_message: ${{ steps.check_commit.outputs.commit_message }}
    steps:
      - name: Check for deploy keyword in commit message
        id: check_commit # Le damos un ID al paso para poder referenciarlo
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '\[deploy\]'
          error: "El mensaje del commit debe incluir '[deploy]' para poder desplegar."
          excludeDescription: 'true'
          excludeTitle: 'false'
          checkAllCommitMessages: 'false'

  # --- JOB 2: DESPLIEGUE (DEPENDE DE LA VALIDACIÓN) ---
  deploy:
    # Este job necesita que el job 'validate' haya terminado con éxito.
    needs: validate
    runs-on: ubuntu-latest
    environment: prod # La aprobación manual se pide aquí.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Deploy Bundle
        env:
          DATABRICKS_AUTH_TYPE: pat
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: databricks bundle deploy --target dev